#APP
TEMPLATES_DIRECTORY = 'templates'
CSV_ENCODING_UPLOAD = "utf-8-sig"


#SCRAPER
PARSER = 'lxml'
SLEEP_TIME_INITIAL = 3
SLEEP_TIME_SCROLLING = 1
NUMBER_OF_SCROLLING = 4
SCROLLER = 1000000
CSV_FILENAME = 'scraped_workouts.csv'
CSV_ENCODING = 'utf-8'
